spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collabboard?stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: false
    open-in-view: false
